#!/system/bin/sh

# - no need to set higher
echo '1' > /sys/devices/virtual/block/mtdblock4/queue/iosched/fifo_batch
echo '1' > /sys/devices/virtual/block/mtdblock5/queue/iosched/fifo_batch
echo '1' > /sys/block/mmcblk0/queue/iosched/fifo_batch

# - adjust the min freq for ondemand governor to save some power
echo '245760' > /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq


exit 0

