#!/system/bin/sh

# - fix fb0 permissions for copybit while camera running
chmod 666 /dev/graphics/fb0

# - remount partitions with noatime
busybox mount -o remount,noatime /data
busybox mount -o remount,noatime /cache

exit 0

